<?php include 'app/views/includes/header.phtml'?>
<div class="container-fluid">
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <h1>Buzz</h1>
        <div class="row">
            <div class="col-md-6">
            <h3>Search for friends</h3>
            </div>
            <div class="col-md-6">
                <a href="/index">back</a>
            </div>
        </div>
        <div class="col-md-9">
            <input type="text" name="search" id="search_text" placeholder="Search" class="form-control" onkeyup="search()" />
        </div>
    </div>
    <div class="clear"></div>
    <div id="content" class="row">
    </div>
</div>
</body>
</html>
<script src="/app/public/js/addfriend.js"></script>
