<?php include 'app/views/includes/header.phtml';
use \App\helpers\session;
$session=new session();
        $session->createSession();

        if(!$session->isLogged()){
            header('location: /login');
        }
?>
<div id="wrapper">
    <h1>Buzz</h1>
    <ul id='adminmenu'>
        <li><a href='/logout'>logout</a></li>
        <li><a href="/addfriend">Add friend</a></li>
    </ul>
    <div class='clear'></div>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <button class="form-control col-md-5" onclick="sentReq()">Sent requests</button>
            <div class="sentReq alert col-md-7">
                <strong>No!</strong> Sent request
            </div>
        </div>
        <div class="col-md-6">
            <button class="form-control col-md-5" onclick="friendReq()">Friend requests &nbsp<span id="count"></span></button>
            <div class="alert friendReq col-md-12">
                <strong>No!</strong> Friend request
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div>
        <input type="text" name="search" id="search_text" placeholder="Search your friends" class="form-control" onkeyup="getF()" />
    </div>
    <div class="clear"></div>
    <table id="result">
    </table>
</div>
<div>
    <h4>online users</h4>
</div>
<?php echo $_SESSION['userName'];?>
<script>
    function friendReq(){
        $(".friendReq").slideToggle();

        $.ajax({
            url:'/index',
            method: 'POST',
            dataType: 'json',
            data: {
                action:'list',
                },
            success: function (data) {
                console.log(data);
                html1='';
                if (!Object.keys(data).length){html1+='<strong>No!</strong> friend request'}
                else {
                    $.each(data, function (index, data) {
                        html1 += '<div class="row">';
                        html1 += '<a href="/profile/' + data.sendFriend + '" class="col-md-4">' + data.sendFriend + '</a>';
                        html1 += '<button  class="btn btn-primary" onclick="acceptReq(\'' + data.sendFriend + '\')">accept friend</button>';
                        html1 += '<div class="divider"/>';
                        html1 += '<button  class="btn btn-primary " onclick="deleteReq(\'' + data.sendFriend + '\')">delete request</button>';
                        html1 += '</div>';
                        html1 += '<hr>';
                    });
                }
                $('.friendReq').html(html1);
                removeUnseen();
                unseenF();
                getF();

            }
        });
    }
    function sentReq(){
        $(".sentReq").slideToggle();

        $.ajax({
            url:'/index',
            method: 'POST',
            dataType: 'json',
            data: {
                action:'listSent',
            },
            success: function (data) {
                console.log(data);
                html='';
                if (!Object.keys(data).length){html+='<strong>No!</strong> sent request'}
                else{
                $.each(data, function(index, data) {
                    html+='<div class="row">';
                    html+='<a href="/profile/'+data.acceptFriend+'" class="col-md-4">'+data.acceptFriend+'</a>';
                    html+='<button  class="btn btn-primary" onclick="cancelReq(\'' + data.acceptFriend + '\')">cancel Request</button>';
                    html+='</div>';
                    html+='<hr>';
                });}
                $('.sentReq').html(html);


            }
        });
    }
    function cancelReq(friend) {

        $.ajax({
            url:'/index',
            method: 'POST',
            data: {
                action:'cancelReq',
                friend: friend},
            success: function (data) {
                //console.log(data)
                alert(data);
                sentReq();
            }
        });
    }
    function deleteReq(friend) {

        $.ajax({
            url:'/index',
            method: 'POST',
            data: {
                action:'deleteReq',
                friend: friend},
            success: function (data) {
                //console.log(data)
                alert(data);
                friendReq();
            }
        });
    }

    function acceptReq(friend) {

        $.ajax({
            url:'/index',
            method: 'POST',
            data: {
                action:'acceptReq',
                friend: friend},
            success: function (data) {
                //console.log(data)
                alert(data);
                friendReq();
                $("#result").load(location.href + " #result");
            }
        });
    }

    function deluser(friend)
    {
        if (confirm("Are you sure you want to delete this"))
        {
                $.ajax({
                    url:'/index',
                    method: 'POST',
                    data: {
                        action:'deleteFriend',
                        friend: friend},
                    success: function (data) {
                        //console.log(data)
                        alert(data);
                        //$("#result").load(location.href + " #result");
                        getF();
                    }
                });

        }
    }
    function getF() {
        var txt = $('#search_text').val();
        console.log(txt);
        if(!txt)
        {
        $.ajax({
            url: '/index',
            method: 'POST',
            dataType: 'json',
            data: {
                action: 'getFriends'
            },
            success: function (data) {
                console.log(data);
                html2='<tr><th>Username</th><th>Name</th><th>Action</th></tr>';
                    $.each(data, function(index, data) {
                        html2+='<tr>';
                        html2+='<td><a href="/profile/'+data.acceptFriend+'">'+data.username+ '</a></td>';
                        html2+='<td>'+data.firstName+ '&nbsp'+ data.lastName+ '</td>';
                        html2+='<td>';
                        html2+='<a href="/profile/'+data.acceptFriend+'">chat</a> |';
                        html2+='<a href="javascript:deluser(\''+data.username+'\')">Delete</a>';
                        html2+='</td>';
                        html2+='</tr>';
                    });
                $('#result').html(html2);


            }
        });
        }
        else
        {
            $.ajax({
                url: '/index',
                method: 'POST',
                dataType: 'json',
                data: {
                    action: 'searchFriends',
                    search: txt
                },
                success: function (data) {
                    console.log(data);
                    html2='<tr><th>Username</th><th>Name</th><th>Action</th></tr>';
                    $.each(data, function(index, data) {
                        html2+='<tr>';
                        html2+='<td><a href="/profile/'+data.acceptFriend+'">'+data.username+ '</a></td>';
                        html2+='<td>'+data.firstName+ '&nbsp'+ data.lastName+ '</td>';
                        html2+='<td>';
                        html2+='<a href="/profile/'+data.acceptFriend+'">chat</a> |';
                        html2+='<a href="javascript:deluser(\''+data.username+'\')">Delete</a>';
                        html2+='</td>';
                        html2+='</tr>';
                    });
                    $('#result').html(html2);


                }
            });

        }
    }
    //get the unseen friend request
    function unseenF()
    {
        $.ajax({
            url:'/index',
            method: 'POST',
            data: {
                action:'unseenF'
               },
            success: function (data) {
                console.log(data);
                if (data === '0'){$('#count').text('').attr("class","")}
                else{$('#count').text(data).attr("class","count")}
                //alert(data);

            }
        });
        setTimeout(unseenF, 5*1000);
    }

    function removeUnseen()
    {
        $.ajax({
            url:'/index',
            method: 'POST',
            data: {
                action:'removeUnseen'
            },
            success: function (data) {
                //console.log(data);
                //$('#count').text(data);
                //alert(data);

            }
        });
    }
    $(document).ready(function() {
        getF();
        unseenF();
        });
</script>
