<?php include 'app/views/includes/header.phtml'?>
<div id="wrapper">
    <h1>Buzz</h1>
    <ul id='adminmenu'>
        <li><a href='/logout'>logout</a></li>
        <li><a href="/addfriend">Add friend</a></li>
    </ul>
    <div class='clear'></div>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <button class="form-control col-md-5" onclick="sentReq()">Sent requests</button>
            <div class="sentReq alert col-md-7">
                <strong>No!</strong> Sent request
            </div>
        </div>
        <div class="col-md-6">
            <button class="form-control col-md-5" onclick="friendReq()">Friend requests</button>
            <div class="alert friendReq col-md-12">
                <strong>No!</strong> Friend request
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <table id="result">
        <tr>
            <th>Username</th>
            <th>Name</th>
            <th>Action</th>
        </tr>
        <?php
        foreach ($this->friends as $friend) {
            echo '<tr>';
            echo '<td>' . $friend['username'] . '</td>';
            echo '<td>' . $friend['firstName']. '&nbsp'. $friend['lastName']. '</td>';


            ?>
            <td>
                <a href="<?php echo '/profile/'.$friend['username']; ?>">view</a> |
                <a href="javascript:deluser('<?php echo $friend['username']; ?>')">Delete</a>
            </td>
            <?php
            echo '</tr>';
        }

        ?>
    </table>
</div>
<?php echo $_SESSION['userName'];?>
<script>
    function friendReq(){
        $(".friendReq").slideToggle();

        $.ajax({
            url:'/index',
            method: 'POST',
            dataType: 'json',
            data: {
                action:'list',
                },
            success: function (data) {
                console.log(data);
                html1='';
                if (!Object.keys(data).length){html1+='<strong>No!</strong> friend request'}
                else {
                    $.each(data, function (index, data) {
                        html1 += '<div class="row">';
                        html1 += '<a href="/profile/' + data.sendFriend + '" class="col-md-4">' + data.sendFriend + '</a>';
                        html1 += '<button  class="btn btn-primary" onclick="acceptReq(\'' + data.sendFriend + '\')">accept friend</button>';
                        html1 += '<div class="divider"/>';
                        html1 += '<button  class="btn btn-primary " onclick="deleteReq(\'' + data.sendFriend + '\')">delete request</button>';
                        html1 += '</div>';
                        html1 += '<hr>';
                    });
                }
                $('.friendReq').html(html1);

            }
        });
    }
    function sentReq(){
        $(".sentReq").slideToggle();

        $.ajax({
            url:'/index',
            method: 'POST',
            dataType: 'json',
            data: {
                action:'listSent',
            },
            success: function (data) {
                console.log(data);
                html='';
                if (!Object.keys(data).length){html+='<strong>No!</strong> sent request'}
                else{
                $.each(data, function(index, data) {
                    html+='<div class="row">';
                    html+='<a href="/profile/'+data.acceptFriend+'" class="col-md-4">'+data.acceptFriend+'</a>';
                    html+='<button  class="btn btn-primary" onclick="cancelReq(\'' + data.acceptFriend + '\')">cancel Request</button>';
                    html+='</div>';
                    html+='<hr>';
                });}
                $('.sentReq').html(html);


            }
        });
    }
    function cancelReq(friend) {

        $.ajax({
            url:'/index',
            method: 'POST',
            data: {
                action:'cancelReq',
                friend: friend},
            success: function (data) {
                //console.log(data)
                alert(data);
                sentReq();
            }
        });
    }
    function deleteReq(friend) {

        $.ajax({
            url:'/index',
            method: 'POST',
            data: {
                action:'deleteReq',
                friend: friend},
            success: function (data) {
                //console.log(data)
                alert(data);
                friendReq();
            }
        });
    }

    function acceptReq(friend) {

        $.ajax({
            url:'/index',
            method: 'POST',
            data: {
                action:'acceptReq',
                friend: friend},
            success: function (data) {
                //console.log(data)
                alert(data);
                friendReq();
                $("#result").load(location.href + " #result");
            }
        });
    }

    function deluser(friend)
    {
        if (confirm("Are you sure you want to delete this"))
        {
                $.ajax({
                    url:'/index',
                    method: 'POST',
                    data: {
                        action:'deleteFriend',
                        friend: friend},
                    success: function (data) {
                        //console.log(data)
                        alert(data);
                        $("#result").load(location.href + " #result");
                    }
                });

        }
    }
</script>
