<?php include 'app/views/includes/header.phtml';
use \App\helpers\session;
$session=new session();
        $session->createSession();

        if(!$session->isLogged()){
            header('location: /login');
        }
?>
<div id="wrapper">
    <h1>Buzz</h1>
    <ul id='adminmenu'>
        <li>hi - <?php echo $_SESSION['userName'];?> &nbsp<a href='/logout'>logout</a></li>
        <li><a href="/addfriend">Add friend</a></li>
    </ul>
    <div class='clear'></div>
    <hr />
    <div class="row">
        <div class="col-md-6">
            <button class="form-control col-md-5" onclick="sentReq()">Sent requests</button>
            <div class="sentReq alert col-md-7">
                <strong>No!</strong> Sent request
            </div>
        </div>
        <div class="col-md-6">
            <button class="form-control col-md-5" onclick="friendReq()">Friend requests &nbsp<span id="count"></span></button>
            <div class="alert friendReq col-md-12">
                <strong>No!</strong> Friend request
            </div>
        </div>
    </div>
    <div class="clear"></div>
    <div>
        <input type="text" name="search" id="search_text" placeholder="Search your friends" class="form-control" onkeyup="getF()" />
    </div>
    <div class="clear"></div>
    <table id="result">
    </table>
</div>
<div id="userChat"></div>
<script src="/app/public/js/main.js"></script>