<?php include 'app/views/includes/header.phtml'?>
<body id="LoginForm">
<div class="container">
    <h1 class="form-heading">buzz</h1>
    <div class="login-form">
        <div class="main-div">
            <div class="panel">
                <h2>Login</h2>
                <p>Please enter your username and password</p>
            </div>
            <form id="Login" method="post" action="/login">
                <?php
                if(isset($this->error)){
                    foreach($this->error as $error1){
                    echo '<p class="error">'.$error1.'</p>';
                    }
                }
                ?>
                <div class="form-group">


                    <input type="text" class="form-control" id="inputEmail" placeholder="Username" name="username">

                </div>

                <div class="form-group">

                    <input type="password" class="form-control" id="inputPassword" placeholder="Password" name="password">

                </div>
                <div class="forgot">
                    <a href="reset.html">Forgot password?</a>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>

            </form>
        </div>
    </div></div>


</body>
</html>
